import type { Metadata } from "next";
import { redirect } from "next/navigation";
import Link from "next/link";
import { getCurrentStaff } from "@/lib/auth/get-current-staff";
import { createClient } from "@/lib/supabase/server";
import type { Database } from "@/types/database";

type IncidentStatus = Database["public"]["Enums"]["incident_status"];
type Incident = Database["public"]["Tables"]["incidents"]["Row"];
export const metadata: Metadata = { title: "প্রশাসনিক ড্যাশবোর্ড | রুখেদাও" };
const statusLabels: Record<string,string> = { all:"সব",pending:"অপেক্ষমাণ",under_review:"পর্যালোচনাধীন",needs_revision:"সংশোধন দরকার",approved:"অনুমোদিত",rejected:"প্রত্যাখ্যাত",archived:"সংরক্ষিত" };
function formatDate(value:string){ return new Intl.DateTimeFormat("bn-BD",{day:"numeric",month:"short",year:"numeric",timeZone:"Asia/Dhaka"}).format(new Date(`${value}T00:00:00+06:00`)); }
export default async function AdminDashboardPage({ searchParams }:{searchParams:Promise<{status?:string;category?:string;division?:string;district?:string;q?:string}>}) {
 const staff=await getCurrentStaff(); if(!staff) redirect("/admin/login"); const f=await searchParams; const supabase=await createClient(); const currentStatus=f.status as IncidentStatus|undefined;
 const [catRes,divRes,distRes,allRes,reportsRes]=await Promise.all([supabase.from("categories").select("id,name").order("sort_order"),supabase.from("divisions").select("id,name").order("sort_order"),supabase.from("districts").select("id,name,division_id").order("sort_order"),supabase.from("incidents").select("id,status"),supabase.from("incident_reports").select("id")]);
 const categories=catRes.data??[], divisions=divRes.data??[], districts=distRes.data??[], all=allRes.data??[]; const counts={total:all.length,pending:all.filter(i=>i.status==="pending").length,under_review:all.filter(i=>i.status==="under_review").length,needs_revision:all.filter(i=>i.status==="needs_revision").length,approved:all.filter(i=>i.status==="approved").length,rejected:all.filter(i=>i.status==="rejected").length,archived:all.filter(i=>i.status==="archived").length};
 let query=supabase.from("incidents").select("*").order("created_at",{ascending:false}); if(currentStatus&&statusLabels[currentStatus]) query=query.eq("status",currentStatus); if(f.category) query=query.eq("category_id",f.category); if(f.division) query=query.eq("division_id",Number(f.division)); if(f.district) query=query.eq("district_id",Number(f.district)); if(f.q?.trim()){const q=f.q.trim().replace(/[%_,]/g," ");query=query.or(`public_id.ilike.%${q}%,title.ilike.%${q}%`)} const {data}=await query; const list=(data??[]) as Incident[];
 const cats=new Map(categories.map(c=>[c.id,c.name])), divs=new Map(divisions.map(d=>[d.id,d.name])), dists=new Map(districts.map(d=>[d.id,d.name])); const params=(extra:Record<string,string|undefined>)=>{const p=new URLSearchParams();for(const [k,v] of Object.entries({...f,...extra}))if(v)p.set(k,v);return `/admin?${p.toString()}`};
 return <main className="mx-auto max-w-7xl px-6 py-10 lg:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-3xl font-bold">প্রশাসনিক ড্যাশবোর্ড</h1><p className="mt-1 text-sm text-zinc-500">স্বাগতম, {staff.staff.display_name} ({staff.staff.role==="admin"?"অ্যাডমিন":"মডারেটর"})</p></div><div className="flex gap-2"><Link href="/admin/reports" className="rounded-xl border px-4 py-2 text-xs font-semibold dark:border-zinc-700">অভিযোগ ({reportsRes.data?.length??0})</Link>{staff.staff.role==="admin"&&<Link href="/admin/staff" className="rounded-xl border px-4 py-2 text-xs font-semibold dark:border-zinc-700">স্টাফ</Link>}</div></div>
 <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-4">{[["অপেক্ষমাণ ঘটনা",counts.pending],["পর্যালোচনাধীন",counts.under_review],["অনুমোদিত ঘটনা",counts.approved],["মোট ঘটনা",counts.total]].map(([l,c])=><div key={String(l)} className="rounded-2xl border bg-white p-5 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><p className="text-xs text-zinc-500">{String(l)}</p><p className="mt-2 text-3xl font-bold">{String(c)}</p></div>)}</div>
 <div className="mt-8 flex flex-wrap gap-2">{Object.entries(statusLabels).map(([id,label])=><Link key={id} href={params({status:id==="all"?undefined:id})} className={`rounded-xl px-3.5 py-2 text-xs font-semibold ${((id==="all"&&!currentStatus)||currentStatus===id)?"bg-zinc-950 text-white":"border bg-white dark:border-zinc-800 dark:bg-zinc-900"}`}>{label}{id==="all"?` (${counts.total})`:id in counts?` (${counts[id as keyof typeof counts]})`:""}</Link>)}</div>
 <form className="mt-5 grid gap-3 rounded-2xl border bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900 sm:grid-cols-2 lg:grid-cols-5"><input name="q" defaultValue={f.q} placeholder="পরিচিতি নম্বর বা শিরোনাম খুঁজুন" className="h-10 rounded-xl border px-3 text-sm dark:border-zinc-700 dark:bg-zinc-800"/><select name="category" defaultValue={f.category??""} className="h-10 rounded-xl border px-3 text-sm dark:border-zinc-700 dark:bg-zinc-800"><option value="">সব ঘটনার ধরন</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select name="division" defaultValue={f.division??""} className="h-10 rounded-xl border px-3 text-sm dark:border-zinc-700 dark:bg-zinc-800"><option value="">সব বিভাগ</option>{divisions.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select name="district" defaultValue={f.district??""} className="h-10 rounded-xl border px-3 text-sm dark:border-zinc-700 dark:bg-zinc-800"><option value="">সব জেলা</option>{districts.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="h-10 rounded-xl bg-zinc-950 px-4 text-xs font-semibold text-white dark:bg-white dark:text-zinc-950">খুঁজুন</button></form>
 <div className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-stone-50 text-xs text-zinc-500 dark:border-zinc-800 dark:bg-zinc-950"><tr>{["পরিচিতি","শিরোনাম","ঘটনার ধরন","স্থান","তারিখ","অবস্থা","কাজ"].map(h=><th key={h} className="px-6 py-4">{h}</th>)}</tr></thead><tbody className="divide-y dark:divide-zinc-800">{list.map(i=><tr key={i.id}><td className="px-6 py-4 font-mono text-xs font-bold">{i.public_id}</td><td className="max-w-xs truncate px-6 py-4 font-medium">{i.title}</td><td className="px-6 py-4 text-xs">{cats.get(i.category_id)||"—"}</td><td className="px-6 py-4 text-xs">{[dists.get(i.district_id),divs.get(i.division_id)].filter(Boolean).join(", ")}</td><td className="px-6 py-4 text-xs">{formatDate(i.incident_date)}</td><td className="px-6 py-4 text-xs">{statusLabels[i.status]}</td><td className="px-6 py-4"><Link href={`/admin/incidents/${i.public_id}`} className="rounded-lg bg-zinc-950 px-3 py-2 text-xs font-semibold text-white dark:bg-white dark:text-zinc-950">পর্যালোচনা</Link></td></tr>)}</tbody></table></div>{list.length===0&&<p className="p-12 text-center text-sm text-zinc-500">কোনো ঘটনা পাওয়া যায়নি।</p>}</div></main>;
}
