import type { Metadata } from "next";
import { redirect } from "next/navigation";
import Link from "next/link";
import { getCurrentStaff } from "@/lib/auth/get-current-staff";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = { title: "কার্যক্রমের ইতিহাস | রুখেদাও" };
const labels: Record<string,string> = { incident_edited:"ঘটনা সম্পাদনা", incident_redacted:"ব্যক্তিগত তথ্য বাদ", status_changed:"অবস্থা পরিবর্তন", verification_changed:"যাচাইয়ের অবস্থা পরিবর্তন", published:"প্রকাশ করা হয়েছে", unpublished:"প্রকাশ বন্ধ", archived:"সংরক্ষণ করা হয়েছে", restored:"আবার প্রকাশ", report_reviewed:"অভিযোগ পর্যালোচনা", report_dismissed:"অভিযোগ গ্রহণ করা হয়নি", report_action_taken:"অভিযোগের ভিত্তিতে ব্যবস্থা" };
function stamp(v:string){return new Intl.DateTimeFormat("bn-BD",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Dhaka"}).format(new Date(v));}
export default async function AdminActivityPage({searchParams}:{searchParams:Promise<{action?:string;actor?:string}>}){
 const staff=await getCurrentStaff();if(!staff)redirect("/admin/login");const f=await searchParams;const supabase=await createClient();
 const [actionsRes,staffRes,incidentsRes]=await Promise.all([supabase.from("moderation_actions").select("id,action,actor_id,incident_id,incident_report_id,from_status,to_status,reason,created_at").order("created_at",{ascending:false}).limit(300),supabase.from("admin_users").select("id,display_name,role,is_active").order("display_name"),supabase.from("incidents").select("id,public_id,title")]);
 const actions=actionsRes.data??[], people=staffRes.data??[], incidents=incidentsRes.data??[];const person=new Map(people.map(x=>[x.id,x]));const incident=new Map(incidents.map(x=>[x.id,x]));const filtered=actions.filter(a=>(!f.action||a.action===f.action)&&(!f.actor||a.actor_id===f.actor));
 const actionTypes=[...new Set(actions.map(a=>a.action))];
 return <main className="mx-auto max-w-7xl px-6 py-10 lg:px-8"><div><Link href="/admin" className="text-xs font-semibold text-zinc-500">← ড্যাশবোর্ড</Link><h1 className="mt-3 text-3xl font-bold">কার্যক্রমের ইতিহাস</h1><p className="mt-1 text-sm text-zinc-500">Immutable moderation_actions থেকে audit trail।</p></div>
 <form className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900 sm:grid-cols-3"><select name="action" defaultValue={f.action??""} className="h-10 rounded-xl border px-3 text-sm dark:border-zinc-700 dark:bg-zinc-800"><option value="">সব কার্যক্রম</option>{actionTypes.map(a=><option key={a} value={a}>{labels[a]??a}</option>)}</select><select name="actor" defaultValue={f.actor??""} className="h-10 rounded-xl border px-3 text-sm dark:border-zinc-700 dark:bg-zinc-800"><option value="">সব স্টাফ</option>{people.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select><button className="h-10 rounded-xl bg-zinc-950 px-4 text-xs font-semibold text-white dark:bg-white dark:text-zinc-950">ফিল্টার করুন</button></form>
 <section className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><div className="divide-y dark:divide-zinc-800">{filtered.map(a=>{const p=person.get(a.actor_id);const i=a.incident_id?incident.get(a.incident_id):null;return <div key={a.id} className="p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold">{labels[a.action]??a.action}</p><p className="mt-1 text-xs text-zinc-500">{p?.display_name??"অজানা স্টাফ"}{p?.role?` · ${p.role==="admin"?"অ্যাডমিন":"মডারেটর"}`:""}</p></div><time className="text-xs text-zinc-400">{stamp(a.created_at)}</time></div><div className="mt-3 flex flex-wrap gap-3 text-xs">{i&&<Link href={`/admin/incidents/${i.public_id}`} className="font-mono font-semibold underline">{i.public_id}</Link>}{a.from_status&&a.to_status&&<span>{a.from_status} → {a.to_status}</span>}{a.reason&&<span className="text-zinc-500">কারণ: {a.reason}</span>}</div></div>})}{filtered.length===0&&<p className="p-12 text-center text-sm text-zinc-500">কোনো কার্যক্রম পাওয়া যায়নি।</p>}</div></section></main>;
}
