"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Staff = { id: string; auth_user_id: string; display_name: string; role: "admin" | "moderator"; is_active: boolean; created_at: string };
export function StaffManagement({ staff }: { staff: Staff[] }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [loading, setLoading] = useState<string | null>(null); const activeAdmins=staff.filter(s=>s.is_active&&s.role==="admin").length;
  async function action(body: Record<string, unknown>, key: string) { setLoading(key); setMessage(""); try { const res = await fetch("/api/admin/staff", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await res.json().catch(() => null); if (!res.ok) { setMessage(data?.message || "কাজটি করা যায়নি।"); return; } setMessage("পরিবর্তন সফল হয়েছে।"); router.refresh(); } catch { setMessage("সার্ভারে যোগাযোগ করা যায়নি।"); } finally { setLoading(null); } }
  return <div>{message && <p className="mb-5 rounded-xl border border-zinc-200 bg-white p-4 text-sm dark:border-zinc-800 dark:bg-zinc-900">{message}</p>}<div className="mb-4 rounded-xl border bg-zinc-50 p-4 text-xs leading-6 text-zinc-600 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300"><strong>অ্যাডমিন নিরাপত্তা:</strong> সিস্টেমে অন্তত একজন active admin থাকা বাধ্যতামূলক। বর্তমানে active admin: {activeAdmins} জন।</div><div className="overflow-hidden rounded-3xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-stone-50 text-xs text-zinc-500 dark:border-zinc-800 dark:bg-zinc-950"><tr><th className="px-6 py-4">নাম</th><th className="px-6 py-4">Auth user ID</th><th className="px-6 py-4">ভূমিকা</th><th className="px-6 py-4">অবস্থা</th><th className="px-6 py-4">কাজ</th></tr></thead><tbody className="divide-y dark:divide-zinc-800">{staff.map(s => { const lastAdmin=s.is_active&&s.role==="admin"&&activeAdmins<=1; return <tr key={s.id}><td className="px-6 py-4 font-semibold">{s.display_name}</td><td className="px-6 py-4 font-mono text-[10px] text-zinc-500">{s.auth_user_id}</td><td className="px-6 py-4"><select disabled={loading !== null||lastAdmin} title={lastAdmin?"সিস্টেমে অন্তত একজন active admin থাকা বাধ্যতামূলক।":undefined} value={s.role} onChange={e => action({ operation: "role", authUserId: s.auth_user_id, role: e.target.value }, `role-${s.id}`)} className="rounded-lg border px-2 py-1 text-xs dark:border-zinc-700 dark:bg-zinc-900"><option value="admin">অ্যাডমিন</option><option value="moderator">মডারেটর</option></select>{lastAdmin&&<p className="mt-1 text-[10px] text-zinc-400">শেষ active admin</p>}</td><td className="px-6 py-4 text-xs">{s.is_active ? "সক্রিয়" : "নিষ্ক্রিয়"}</td><td className="px-6 py-4">{s.is_active && <button type="button" disabled={loading !== null||lastAdmin} title={lastAdmin?"সিস্টেমে অন্তত একজন active admin থাকা বাধ্যতামূলক।":undefined} onClick={() => { if (confirm("এই স্টাফকে নিষ্ক্রিয় করতে চান?")) action({ operation: "deactivate", authUserId: s.auth_user_id }, `deactivate-${s.id}`); }} className="rounded-lg border border-zinc-300 px-3 py-2 text-xs font-semibold disabled:cursor-not-allowed disabled:opacity-40 dark:border-zinc-700">নিষ্ক্রিয় করুন</button>}</td></tr>})}</tbody></table></div>{staff.length === 0 && <p className="p-12 text-center text-sm text-zinc-500">কোনো স্টাফ পাওয়া যায়নি।</p>}</div><p className="mt-4 text-xs leading-6 text-zinc-500">নতুন স্টাফ যোগ করতে Supabase Auth-এ আগে ব্যবহারকারী তৈরি থাকতে হবে। এখানে frozen database-এর বিদ্যমান staff function ব্যবহার করা হয়।</p></div>;
}
