import type { Metadata } from "next";
import { IncidentLedgerSidebar } from "@/components/incident/incident-ledger-sidebar";
import { NewIncidentForm } from "@/components/incident/new-incident-form";
import { Breadcrumbs } from "@/components/layout/breadcrumbs";
import { getHomeLedgerData } from "@/features/home/get-home-ledgers";
import { createClient } from "@/lib/supabase/server";

type Category = { id: string; name: string }; type Division = { id: number; name: string }; type District = { id: number; division_id: number; name: string };
export const dynamic = "force-dynamic"; export const revalidate = 0;
export const metadata: Metadata = { title: "ঘটনা জানান", description: "পরিচয় গোপন রেখে একটি গুরুত্বপূর্ণ ঘটনা জানান।", robots: { index: false, follow: true, googleBot: { index: false, follow: true } } };
export default async function NewIncidentPage() {
  const supabase = await createClient(); const [ledgers, categoriesResult, divisionsResult, districtsResult] = await Promise.all([getHomeLedgerData(), supabase.from("public_categories").select("id,name").order("sort_order", { ascending: true }), supabase.from("public_divisions").select("id,name").order("sort_order", { ascending: true }), supabase.from("public_districts").select("id,division_id,name").order("division_id", { ascending: true }).order("sort_order", { ascending: true })]);
  const referenceError = categoriesResult.error || divisionsResult.error || districtsResult.error; if (referenceError) console.error("Incident reference data failed to load", referenceError);
  const categoryOptions: Category[] = (categoriesResult.data ?? []).flatMap((item) => item.id && item.name ? [{ id: item.id, name: item.name }] : []); const divisionOptions: Division[] = (divisionsResult.data ?? []).flatMap((item) => item.id !== null && item.name ? [{ id: item.id, name: item.name }] : []); const districtOptions: District[] = (districtsResult.data ?? []).flatMap((item) => item.id !== null && item.division_id !== null && item.name ? [{ id: item.id, division_id: item.division_id, name: item.name }] : []);
  return <main className="flex-1 bg-stone-50 text-zinc-950"><section className="border-b border-zinc-200 bg-white"><div className="mx-auto max-w-7xl px-6 py-5 lg:px-8"><Breadcrumbs items={[{ label: "ঘটনা জানান" }]} homeLabel="প্রচ্ছদ" /></div></section><section className="mx-auto max-w-7xl px-6 py-10 lg:px-8 lg:py-14"><div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_320px] lg:items-start"><div><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">ঘটনা জানান</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">পরিচয় গোপন রেখে ঘটনা জানান</h1><p className="mt-4 max-w-2xl text-base leading-7 text-zinc-600 sm:text-lg">জনস্বার্থের গুরুত্বপূর্ণ ঘটনা সহজভাবে জানান। কোনো অ্যাকাউন্ট বা প্রোফাইলের প্রয়োজন নেই।</p></div><div className="border border-zinc-200 bg-white p-5 shadow-sm sm:p-8 lg:p-10">{referenceError ? <div className="border border-red-200 bg-red-50 p-5" role="alert"><p className="text-sm font-semibold text-red-900">তথ্য লোড করা যায়নি</p><p className="mt-2 text-sm leading-6 text-red-800">কিছুক্ষণ পর আবার চেষ্টা করুন।</p></div> : <NewIncidentForm categories={categoryOptions} divisions={divisionOptions} districts={districtOptions} labels={{ eyebrow: "ঘটনা জানান", title: "পরিচয় গোপন রেখে ঘটনা জানান", description: "জনস্বার্থের গুরুত্বপূর্ণ ঘটনা সহজভাবে জানান। কোনো অ্যাকাউন্ট বা প্রোফাইলের প্রয়োজন নেই।", privacyTitle: "আপনার পরিচয় গোপন থাকবে", privacyDescription: "ঘটনা জানাতে কোনো অ্যাকাউন্ট, প্রোফাইল বা লগইন করতে হয় না।", titleLabel: "ঘটনার শিরোনাম", titlePlaceholder: "ঘটনাটি সংক্ষেপে লিখুন", descriptionLabel: "ঘটনার বিবরণ", descriptionPlaceholder: "কী ঘটেছে, কোথায় এবং কখন ঘটেছে—প্রয়োজনীয় তথ্য লিখুন", dateLabel: "ঘটনার তারিখ", categoryLabel: "ঘটনার ধরন", divisionLabel: "বিভাগ", districtLabel: "জেলা", categoryPlaceholder: "ঘটনার ধরন বেছে নিন", divisionPlaceholder: "বিভাগ বেছে নিন", districtPlaceholder: "জেলা বেছে নিন", guidanceTitle: "জমা দেওয়ার আগে", guidanceOne: "তথ্য যতটা সম্ভব পরিষ্কার ও নির্ভুল রাখুন।", guidanceTwo: "নিজের বা অন্য কারও অপ্রয়োজনীয় ব্যক্তিগত তথ্য দেবেন না।", guidanceThree: "জমা দেওয়ার পর পাওয়া পরিচিতি নম্বরটি সংরক্ষণ করুন।", submit: "ঘটনা জমা দিন", submitting: "জমা দেওয়া হচ্ছে…", successTitle: "ঘটনা জমা হয়েছে", successDescription: "আপনার পরিচিতি নম্বরটি সংরক্ষণ করুন। এটি দিয়ে পরে আপনার জমা দেওয়া ঘটনার অবস্থা জানা যাবে।", publicIdLabel: "পরিচিতি নম্বর", startAnother: "আরেকটি ঘটনা জানান", requiredError: "প্রয়োজনীয় তথ্য পূরণ করুন।", futureDateError: "ভবিষ্যতের তারিখ দেওয়া যাবে না।", invalidError: "তথ্য যাচাই করে আবার চেষ্টা করুন।", referenceError: "তথ্য লোড করা যায়নি।", submitError: "এই মুহূর্তে ঘটনা জমা দেওয়া যাচ্ছে না। পরে আবার চেষ্টা করুন।" }} />}</div></div><IncidentLedgerSidebar ledgers={ledgers} /></div></section></main>;
}
